### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by strayer** [kaibader/KiCad-Libraries#1]
Hi! I'm working on a project that I'd like to release on GitHub with the MIT License. I'll be using a SS-12D00 on/off switch so I was wondering if I could use the kicad footprint of your library. Would you mind if I use the file licensed under the MIT License with acknowledgements?

ref: https://github.com/kaibader/KiCad-Library/blob/main/Footprints/KaiBader.pretty/SS-12D00.kicad_mod

I'd most likely need to modify it too since the PCB will be mirrored and usable from both sides, requiring an additional silkscreen on the back side.

**Comment by kaibader** [comment]
Hi, I usually license private projects under (L)GPL or the MIT license. In case of the Kicad symbols and footprints I think the CC-BY-SA 4.0 is more appropriate. It should be just as permissive and is AFAIK also used for the original Kicad libs.

I've added the respectice LICENSE files to the repos (should have done that long ago - thanks for the hint).

**Comment by strayer** [comment]
Since I'm basing my work on two other projects that are licensed under MIT I feel obliged to go with MIT too, but I think as long as attributions and licensing in the Kicad library reference the CC-BY-SA items it should be fine.

Thanks for clarifying and adding the license file!
